<a name="iniciox"></a>
<div id="contenedor" class="contentAll" >
    <div id="specialLeftSide"></div>    
    <?php echo $this->render('checkout/index/header') ?>
    <table align="center">                
        <?php echo $this->render('checkout/index/form') ?>
        <td width="225px" valign="top">
            <div id="rightSide" width="225px">
                <div id="importantNoticeBox" class="scapeToDetails" <?php echo $this->translate('tDireccionToText') ?> >
                    <div class="secTextFondo colorSection">
                        <p><?php echo $this->translate('tImportant') ?></p>
                    </div>
                    <div class="seText">
                        <p><?php echo $this->translate('tImportant_p') ?></p>
                        <ul>
                            <li><?php echo $this->translate('tImportant_l1') ?></li>
                            <li><?php echo $this->translate('tImportant_l2') ?></li>
                            <li><?php echo $this->translate('tImportant_l3') ?></li>
                        </ul>
                    </div>
                </div>

                <div id="imagesBox" class="scapeToDetails conSubSpace">
                    <div id="imageBoxMcAfee" align="center">12
                        <a target="_blank" href="https://www.mcafeesecure.com/RatingVerify?ref=bongous.com"><img border="0" src="//images.scanalert.com/meter/bongous.com/23.gif" alt="McAfee SECURE sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams" oncontextmenu="alert('Copying Prohibited by Law - McAfee Secure is a Trademark of McAfee, Inc.'); return false;"></a>
                    </div>
                    <div id="imageBoxAccBus" align="center">
                        <a href="http://www.bbb.org/connecticut/business-reviews/mailing-services-international/bongo-international-in-bridgeport-ct-87054397" target="_blank" > </a>
                    </div>
                </div>



                <div id="securityBox" class="scapeToDetails" <?php echo $this->translate('tDireccionToText') ?>>
                    <div class="secTextFondo colorSection">
                        <p><?php echo $this->translate('tSecurity&privacy') ?></p>
                    </div>
                    <div class="seText">
                        <p><?php echo $this->translate('tWeValueThe') ?>.</p>
                    </div>
                </div>

                <div id="centinelMsg" class="scapeToDetails" <?php echo $this->translate('tDireccionToText') ?>>
                    <div>
                        <table>
                            <tr>
                                <td align="center" colspan="2" ><img src="<?php echo $this->server()->getStatic() ?>static/css/images/secure.png"/></td>
                            </tr>
                            <tr>
                                <td align="center"><a class="learn" href="https://www.mastercard.com/securecode" target="_blank"><?php echo $this->translate('tlearmore') ?></a></td>
                                <td align="center"><a class="learn" href="http://usa.visa.com/personal/security/security-program/verified-by-visa.jsp" target="_blank"><?php echo $this->translate('tlearmore') ?></a></td>
                            </tr>
                        </table>
                    </div>
                    <div class="seText">
                        <p><?php echo $this->translate('tSecureVerify') ?></p>
                    </div>                                
                </div>
            </div>                        
        </td>
        </tr>
    </table>
    <div id="specialRightSide"></div>
</div>
<?php echo $this->render('checkout/index/footer') ?>
