<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('PubliKademy'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>    
    <script>
        og = {};
    </script>
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->server()->getStatic() . 'static/css/style.css')
            ->prependStylesheet($this->server()->getStatic() . 'static/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->server()->getStatic() . 'static/css/bootstrap.min.css')
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()
            ->prependFile($this->server()->getStatic() . 'static/js/less/less-1.1.5.min.js')
            ->prependFile($this->server()->getStatic() . 'static/js/bootstrap.min.js')
            ->prependFile($this->server()->getStatic() . 'static/js/jquery.min.js')
            ->prependFile($this->server()->getStatic() . 'static/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->server()->getStatic() . 'static/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ?>
</head>

