alter table bp_order_detail add distribution_country varchar(2);
alter table bp_order_detail add distribution_zip varchar(16);
drop procedure sp_checkout_insert_bp_order_detail;
CREATE PROCEDURE `sp_checkout_insert_bp_order_detail`(
in in_product_id text,
in in_q int,
in in_price float,
in in_idorder_bongoP  int,
in in_titulo text,
in in_custom_1 text,
in in_custom_2 text ,
in in_custom_3 text,
in in_price_origin float,
in in_price_domestic float,
in in_distribution_country varchar(2),
in in_distribution_zip varchar(16)  )
BEGIN
 insert into bp_order_detail(
     product_id,
    q ,
    price ,
    idorder_bongoP ,
    titulo ,
    custom_1 ,
    custom_2 ,
    custom_3,
    price_origin,
    price_domestic,
    distribution_country,
    distribution_zip)
 values(  
  in_product_id,
  in_q ,
  in_price ,
  in_idorder_bongoP ,
  in_titulo ,
  in_custom_1 ,
  in_custom_2 ,
  in_custom_3,
  in_price_origin,
  in_price_domestic,
  in_distribution_country,
  in_distribution_zip);
 select LAST_INSERT_ID() as ou_lastinsertid;
END;

update bp_order set transaction_id=null;
alter table bp_order add fecha_creacion_dbmaster datetime;
alter table bp_order add unique (transaction_id)

drop procedure sp_master_insert_bporder;
CREATE  PROCEDURE `sp_master_insert_bporder`(
                 in in_date text,
           in in_customer_firstname text,
           in in_customer_lastname text,
           in in_customer_ip text,
           in in_customer_company text ,
           in in_customer_address1 text,
           in in_customer_address2 text,
           in in_customer_city text,
           in in_customer_country text,
           in in_customer_state text,
           in in_customer_zip text,
           in in_customer_phone text,
           in in_customer_email text,
           in in_idpartner int,
           in in_DPL text,
           in in_maxmind text,
           in in_maxmind_text text,
           in in_order_subtotal double,
           in in_order_dutyCost double,
           in in_order_taxCost double,
           in in_order_shippingCost double,
           in in_order_insuranceCost double,
           in in_order_adjustment double,
           in in_order_currencyCode text,
           in in_order_ddpAvailable text,
           in in_order_landedCostTransactionID text,
           in in_order_total double,
           in in_estatus text,
           in in_paypal_id text,
           in in_refund text,
           in in_date_cancel text,
           in in_date_process text,
           in in_date_bl text,
           in in_link_retorno text,
           in in_cart_type text,
           in in_valorUSD  text,
           in in_currency text,
           in in_order_shippingCost_domestic text,
           in in_custom_order1 text,
           in in_custom_order2 text,
           in in_custom_order3 text,
           in in_text_post text,
           in in_order_adjustment_amount text,
           in in_order_adjustment_percentage text,
           in in_tax_id text,
           in in_shopping_type text,
           in in_shipping_method text,
           in in_paypal_auto text,
           in in_paypal_auto_estatus text,
           in in_eci text,
           in in_centinel text,
           in in_surchargeOutArea text,
           in in_order_subtotal_origin text,
           in in_order_shippingCost_domestic_origin text,
           in in_acodeAdyen text,
           in in_currency_origin text ,
           in in_currency_fin text,
           in in_rate_origin_fin text,
           in in_rate_origin_dolar text,
           in in_rate_dolar_fin text,
           in in_rate_origin_fin_nouplift text,
           in in_rate_origin_dolar_nouplift text,
           in in_rate_dolar_fin_nouplift text,
           in in_idcountry int,
           in in_intl_ETA datetime,
           in in_SKUDcountry text,
           in in_SKUDcountryZip text,
           in in_transaction_id text)
begin

insert into bp_order(`date`,
           customer_firstname ,
           customer_lastname ,
           customer_ip ,
           customer_company ,
           customer_address1,
           customer_address2,
           customer_city ,
           customer_country ,
           customer_state ,
           customer_zip ,
           customer_phone ,
           customer_email ,
           idpartner ,
           DPL ,
           maxmind ,
           maxmind_text ,
           order_subtotal ,
           order_dutyCost ,
           order_taxCost ,
           order_shippingCost ,
           order_insuranceCost ,
           order_adjustment ,
           order_currencyCode ,
           order_ddpAvailable ,
           order_landedCostTransactionID ,
           order_total ,
           estatus ,
           paypal_id ,
           refund ,
           date_cancel ,
           date_process ,
           date_bl ,
           link_retorno ,
           cart_type ,
           valorUSD ,
           currency ,
           order_shippingCost_domestic ,
           custom_order1 ,
           custom_order2 ,
           custom_order3 ,
           text_post ,
           order_adjustment_amount ,
           order_adjustment_percentage ,
           tax_id ,
           shopping_type ,
           shipping_method ,
           paypal_auto ,
           paypal_auto_estatus ,
           eci ,
           centinel ,
           surchargeOutArea ,
           order_subtotal_origin ,
           order_shippingCost_domestic_origin ,
           acodeAdyen ,
           currency_origin ,
           currency_fin ,
           rate_origin_fin ,
           rate_origin_dolar ,
           rate_dolar_fin ,
           rate_origin_fin_nouplift ,
           rate_origin_dolar_nouplift ,
           rate_dolar_fin_nouplift,
           idcountry,
           intl_ETA,
           SKUDcountry,
           SKUDcountryZip,
           transaction_id,
           fecha_creacion_dbmaster)
values(in_date,
           in_customer_firstname ,
           in_customer_lastname ,
           in_customer_ip ,
           in_customer_company ,
           in_customer_address1 ,
           in_customer_address2 ,
           in_customer_city ,
           in_customer_country ,
           in_customer_state ,
           in_customer_zip ,
           in_customer_phone ,
           in_customer_email ,
           in_idpartner ,
           in_DPL ,
           in_maxmind ,
           in_maxmind_text ,
           in_order_subtotal ,
           in_order_dutyCost ,
           in_order_taxCost ,
           in_order_shippingCost ,
           in_order_insuranceCost ,
           in_order_adjustment ,
           in_order_currencyCode ,
           in_order_ddpAvailable ,
           in_order_landedCostTransactionID ,
           in_order_total ,
           in_estatus ,
           in_paypal_id ,
           in_refund ,
           in_date_cancel ,
           in_date_process ,
           in_date_bl ,
           in_link_retorno ,
           in_cart_type ,
           in_valorUSD  ,
           in_currency ,
           in_order_shippingCost_domestic ,
           in_custom_order1 ,
           in_custom_order2 ,
           in_custom_order3 ,
           in_text_post ,
           in_order_adjustment_amount ,
           in_order_adjustment_percentage ,
           in_tax_id ,
           in_shopping_type ,
           in_shipping_method ,
           in_paypal_auto ,
           in_paypal_auto_estatus ,
           in_eci ,
           in_centinel ,
           in_surchargeOutArea ,
           in_order_subtotal_origin,
           in_order_shippingCost_domestic_origin,
           in_acodeAdyen ,
           in_currency_origin ,
           in_currency_fin,
           in_rate_origin_fin,
           in_rate_origin_dolar ,
           in_rate_dolar_fin,
           in_rate_origin_fin_nouplift ,
           in_rate_origin_dolar_nouplift ,
           in_rate_dolar_fin_nouplift,
           in_idcountry,
           in_intl_ETA,
           in_SKUDcountry,
           in_SKUDcountryZip,
           in_transaction_id,
            now());	           
          select LAST_INSERT_ID() as ou_lastinsertid;	   
end;

drop procedure sp_checkout_cron_transactions;
CREATE PROCEDURE `sp_checkout_cron_transactions`()
BEGIN
    SELECT id, t1.idorder_bongoP,idorder_bongoP_origin FROM bp_order_transaction t1  
    inner join bp_order t2 on t1.idorder_bongoP=t2.idorder_bongoP   
    WHERE t1.estatus = 0
     order by `date` asc;
END;